version: "3"
networks:
  eureka-networks:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: .
    container_name: server-eureka  
    image: netoow10/server-eureka
    ports:
      - "8761:8761"
    networks:
      - eureka-networks
