apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eureka-server-pod
  template:
    metadata:
      name: eureka-server-pod
      labels:
        app: eureka-server-pod
    spec:
      containers:
        - name: eureka-server    
          image: netoow10/eureka-server:latest
          ports:
            - containerPort: 8761
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "300m"
              memory: "256Mi"