apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deploy
  labels:
    app: eureka-server-deploys
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eureka-server-deploys
  template:
    metadata:
      labels:
        app: eureka-server-deploys
    spec:
      containers:
        - name: eureka-server    
          image: netoow10/eureka-server:latest
          ports:
            - containerPort: 8761
          livenessProbe:
            httpGet:
              path: /registry/actuator/health
              port: 8761
            periodSeconds: 5
            failureThreshold: 1  
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /registry/actuator/health
              port: 8761
            periodSeconds: 3
            failureThreshold: 1
          startupProbe: 
            httpGet:
              path: /registry/actuator/health
              port: 8761
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "300m"
              memory: "256Mi"
