apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  selector:
    app: eureka-server-deploys
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      

