name: Continuos Integration Eureka Server
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:latest, ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:${{ github.sha }}    
      
      - name: Setup Kustomaze
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Kubernates Resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          cd k8s
          kustomize edit set image eureka-server=$DOCKER_USERNAME/eureka-server:$GITHUB_SHA

      - name: Commit    
        run: |
          git config --local user.email "luizfullcycle@gmail.com"
          git config --local user.name "Luiz Fernanandes de Oliveira Neto"
          git commit -am "Commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true    
          
